# Config file for automatic testing at travis-ci.org
language: python

env:
    - TOXENV=flake8
    - TOXENV=doc
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35

install:
    - pip install tox

script:
    - tox -e $TOXENV

after_success:
    - coveralls
